name: "Compile & Run Credo"
on:
  workflow_dispatch:

jobs:
  test_on_source:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    name: Run CredoDemoPlugin on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}]
    strategy:
      matrix:
        otp: [20.3, 21.3, 22.2, 23]
        elixir: [1.7.4, 1.8.2, 1.9.4, 1.10.4, 1.11.0]
        exclude:
          - otp: 23
            elixir: 1.7.4
          - otp: 23
            elixir: 1.8.2
          - otp: 23
            elixir: 1.9.4
          - otp: 20.3
            elixir: 1.10.4
          - otp: 20.3
            elixir: 1.11.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix credo --castle Winterfell
      - run: mix credo --mute-exit-status
